/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 97 "./mips.igen"
  itable_RSVD_SPECIAL,
#line 1757 "./mips.igen"
  itable_ADD_SPECIAL,
#line 1777 "./mips.igen"
  itable_ADDI_NORMAL,
#line 1806 "./mips.igen"
  itable_ADDIU_NORMAL,
#line 1835 "./mips.igen"
  itable_ADDU_SPECIAL,
#line 1862 "./mips.igen"
  itable_AND_SPECIAL,
#line 1882 "./mips.igen"
  itable_ANDI_NORMAL,
#line 1902 "./mips.igen"
  itable_BEQ_NORMAL,
#line 1926 "./mips.igen"
  itable_BEQL_NORMAL,
#line 1951 "./mips.igen"
  itable_BGEZ_REGIMM,
#line 1975 "./mips.igen"
  itable_BGEZAL_REGIMM,
#line 2002 "./mips.igen"
  itable_BGEZALL_REGIMM,
#line 2032 "./mips.igen"
  itable_BGEZL_REGIMM,
#line 2057 "./mips.igen"
  itable_BGTZ_NORMAL,
#line 2081 "./mips.igen"
  itable_BGTZL_NORMAL,
#line 2108 "./mips.igen"
  itable_BLEZ_NORMAL,
#line 2134 "./mips.igen"
  itable_BLEZL_NORMAL,
#line 2159 "./mips.igen"
  itable_BLTZ_REGIMM,
#line 2183 "./mips.igen"
  itable_BLTZAL_REGIMM,
#line 2212 "./mips.igen"
  itable_BLTZALL_REGIMM,
#line 2240 "./mips.igen"
  itable_BLTZL_REGIMM,
#line 2267 "./mips.igen"
  itable_BNE_NORMAL,
#line 2291 "./mips.igen"
  itable_BNEL_NORMAL,
#line 2316 "./mips.igen"
  itable_BREAK_SPECIAL,
#line 2583 "./mips.igen"
  itable_DIV_SPECIAL,
#line 2624 "./mips.igen"
  itable_DIVU_SPECIAL,
#line 3020 "./mips.igen"
  itable_J_NORMAL,
#line 3042 "./mips.igen"
  itable_JAL_NORMAL,
#line 3064 "./mips.igen"
  itable_JALR_SPECIAL,
#line 3096 "./mips.igen"
  itable_JR_SPECIAL,
#line 3226 "./mips.igen"
  itable_LB_NORMAL,
#line 3245 "./mips.igen"
  itable_LBU_NORMAL,
#line 3329 "./mips.igen"
  itable_LH_NORMAL,
#line 3348 "./mips.igen"
  itable_LHU_NORMAL,
#line 3367 "./mips.igen"
  itable_LL_NORMAL,
#line 3399 "./mips.igen"
  itable_LUI_NORMAL,
#line 3418 "./mips.igen"
  itable_LW_NORMAL,
#line 3437 "./mips.igen"
  itable_LWCz_NORMAL,
#line 3456 "./mips.igen"
  itable_LWL_NORMAL,
#line 3475 "./mips.igen"
  itable_LWR_NORMAL,
#line 3559 "./mips.igen"
  itable_MFHI_SPECIAL,
#line 3595 "./mips.igen"
  itable_MFLO_SPECIAL,
#line 3623 "./mips.igen"
  itable_MOVN_SPECIAL,
#line 3638 "./mips.igen"
  itable_MOVZ_SPECIAL,
#line 3695 "./mips.igen"
  itable_MTHI_SPECIAL,
#line 3723 "./mips.igen"
  itable_MTLO_SPECIAL,
#line 3781 "./mips.igen"
  itable_MULT_SPECIAL,
#line 3833 "./mips.igen"
  itable_MULTU_SPECIAL,
#line 3876 "./mips.igen"
  itable_NOR_SPECIAL,
#line 3902 "./mips.igen"
  itable_OR_SPECIAL,
#line 3929 "./mips.igen"
  itable_ORI_NORMAL,
#line 3948 "./mips.igen"
  itable_PREF_NORMAL,
#line 4080 "./mips.igen"
  itable_SB_NORMAL,
#line 4099 "./mips.igen"
  itable_SC_NORMAL,
#line 4194 "./mips.igen"
  itable_SH_NORMAL,
#line 4221 "./mips.igen"
  itable_SLLa_SPECIAL,
#line 4264 "./mips.igen"
  itable_SLLV_SPECIAL,
#line 4290 "./mips.igen"
  itable_SLT_SPECIAL,
#line 4316 "./mips.igen"
  itable_SLTI_NORMAL,
#line 4342 "./mips.igen"
  itable_SLTIU_NORMAL,
#line 4369 "./mips.igen"
  itable_SLTU_SPECIAL,
#line 4398 "./mips.igen"
  itable_SRA_SPECIAL,
#line 4429 "./mips.igen"
  itable_SRAV_SPECIAL,
#line 4459 "./mips.igen"
  itable_SRL_SPECIAL,
#line 4489 "./mips.igen"
  itable_SRLV_SPECIAL,
#line 4508 "./mips.igen"
  itable_SUB_SPECIAL,
#line 4536 "./mips.igen"
  itable_SUBU_SPECIAL,
#line 4555 "./mips.igen"
  itable_SW_NORMAL,
#line 4574 "./mips.igen"
  itable_SWCz_NORMAL,
#line 4593 "./mips.igen"
  itable_SWL_NORMAL,
#line 4612 "./mips.igen"
  itable_SWR_NORMAL,
#line 4631 "./mips.igen"
  itable_SYNC_SPECIAL,
#line 4650 "./mips.igen"
  itable_SYSCALL_SPECIAL,
#line 4669 "./mips.igen"
  itable_TEQ_SPECIAL,
#line 4686 "./mips.igen"
  itable_TEQI_REGIMM,
#line 4703 "./mips.igen"
  itable_TGE_SPECIAL,
#line 4720 "./mips.igen"
  itable_TGEI_REGIMM,
#line 4737 "./mips.igen"
  itable_TGEIU_REGIMM,
#line 4754 "./mips.igen"
  itable_TGEU_SPECIAL,
#line 4771 "./mips.igen"
  itable_TLT_SPECIAL,
#line 4788 "./mips.igen"
  itable_TLTI_REGIMM,
#line 4805 "./mips.igen"
  itable_TLTIU_REGIMM,
#line 4822 "./mips.igen"
  itable_TLTU_SPECIAL,
#line 4839 "./mips.igen"
  itable_TNE_SPECIAL,
#line 4856 "./mips.igen"
  itable_TNEI_REGIMM,
#line 4880 "./mips.igen"
  itable_XOR_SPECIAL,
#line 4906 "./mips.igen"
  itable_XORI_NORMAL,
#line 5122 "./mips.igen"
  itable_ABS_fmt_COP1,
#line 5142 "./mips.igen"
  itable_ADD_fmt_COP1,
#line 5202 "./mips.igen"
  itable_BC1b_COP1S,
#line 5240 "./mips.igen"
  itable_C_cond_fmtb_COP1,
#line 5257 "./mips.igen"
  itable_CEIL_L_fmt_COP1,
#line 5273 "./mips.igen"
  itable_CEIL_W_COP1,
#line 5305 "./mips.igen"
  itable_CFC1b_COP1,
#line 5346 "./mips.igen"
  itable_CTC1b_COP1,
#line 5375 "./mips.igen"
  itable_CVT_D_fmt_COP1,
#line 5394 "./mips.igen"
  itable_CVT_L_fmt_COP1,
#line 5424 "./mips.igen"
  itable_CVT_S_fmt_COP1,
#line 5465 "./mips.igen"
  itable_CVT_W_fmt_COP1,
#line 5484 "./mips.igen"
  itable_DIV_fmt_COP1,
#line 5571 "./mips.igen"
  itable_FLOOR_L_fmt_COP1,
#line 5587 "./mips.igen"
  itable_FLOOR_W_fmt_COP1,
#line 5616 "./mips.igen"
  itable_LDC1b_COP1,
#line 5675 "./mips.igen"
  itable_LWC1_COP1,
#line 5694 "./mips.igen"
  itable_LWXC1_COP1X,
#line 5708 "./mips.igen"
  itable_MADD_fmt_COP1X,
#line 5734 "./mips.igen"
  itable_MFC1b_COP1,
#line 5750 "./mips.igen"
  itable_MOV_fmt_COP1,
#line 5771 "./mips.igen"
  itable_MOVtf_SPECIAL,
#line 5787 "./mips.igen"
  itable_MOVtf_fmt_COP1,
#line 5801 "./mips.igen"
  itable_MOVN_fmt_COP1,
#line 5822 "./mips.igen"
  itable_MOVZ_fmt_COP1,
#line 5836 "./mips.igen"
  itable_MSUB_fmt_COP1X,
#line 5863 "./mips.igen"
  itable_MTC1b_COP1,
#line 5879 "./mips.igen"
  itable_MUL_fmt_COP1,
#line 5898 "./mips.igen"
  itable_NEG_fmt_COP1,
#line 5917 "./mips.igen"
  itable_NMADD_fmt_COP1X,
#line 5930 "./mips.igen"
  itable_NMSUB_fmt_COP1X,
#line 5965 "./mips.igen"
  itable_PREFX_COP1X,
#line 6000 "./mips.igen"
  itable_RECIP_fmt_COP1,
#line 6013 "./mips.igen"
  itable_ROUND_L_fmt_COP1,
#line 6029 "./mips.igen"
  itable_ROUND_W_fmt_COP1,
#line 6047 "./mips.igen"
  itable_RSQRT_fmt_COP1,
#line 6070 "./mips.igen"
  itable_SDC1b_COP1,
#line 6129 "./mips.igen"
  itable_SQRT_fmt_COP1,
#line 6147 "./mips.igen"
  itable_SUB_fmt_COP1,
#line 6167 "./mips.igen"
  itable_SWC1_COP1,
#line 6186 "./mips.igen"
  itable_SWXC1_COP1X,
#line 6199 "./mips.igen"
  itable_TRUNC_L_fmt_COP1,
#line 6215 "./mips.igen"
  itable_TRUNC_W_COP1,
#line 6240 "./mips.igen"
  itable_BC0F_COP0,
#line 6263 "./mips.igen"
  itable_BC0FL_COP0,
#line 6278 "./mips.igen"
  itable_BC0T_COP0,
#line 6292 "./mips.igen"
  itable_BC0TL_COP0,
#line 6307 "./mips.igen"
  itable_CACHE_NORMAL,
#line 6356 "./mips.igen"
  itable_ERET_COP0,
#line 6383 "./mips.igen"
  itable_MFC0_COP0,
#line 6403 "./mips.igen"
  itable_MTC0_COP0,
#line 6422 "./mips.igen"
  itable_RFE_COP0,
#line 6437 "./mips.igen"
  itable_COPz_NORMAL,
#line 6456 "./mips.igen"
  itable_TLBP_COP0,
#line 6471 "./mips.igen"
  itable_TLBR_COP0,
#line 6486 "./mips.igen"
  itable_TLBWI_COP0,
#line 6501 "./mips.igen"
  itable_TLBWR_COP0,
  nr_itable_entries,
} itable_index;

typedef enum {
  itable_flag_32,
  itable_flag_f,
  nr_itable_flags,
} itable_flags;
extern const char *itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char *itable_option_names[];

typedef enum {
  itable_processor_dsp,
  itable_processor_dsp2,
  itable_processor_mdmx,
  itable_processor_micromips32,
  itable_processor_micromips64,
  itable_processor_micromipsdsp,
  itable_processor_mips16,
  itable_processor_mips16e,
  itable_processor_mips32,
  itable_processor_mips32r2,
  itable_processor_mips3d,
  itable_processor_mips64,
  itable_processor_mips64r2,
  itable_processor_mipsI,
  itable_processor_mipsII,
  itable_processor_mipsIII,
  itable_processor_mipsIV,
  itable_processor_mipsV,
  itable_processor_r3900,
  itable_processor_sb1,
  itable_processor_smartmips,
  itable_processor_vr4100,
  itable_processor_vr4120,
  itable_processor_vr5000,
  itable_processor_vr5400,
  itable_processor_vr5500,
  nr_itable_processors,
} itable_processors;
extern const char *itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  char *format;
  char *form;
  char *flags;
  char flag[nr_itable_flags + 1];
  char *options;
  char option[nr_itable_options + 1];
  char *processors;
  char processor[nr_itable_processors + 1];
  char *name;
  char *file;
  int line_nr;
} itable_info;

extern itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 8,
  sizeof_itable_name = 12,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
