#ifndef DRIVER_SO_H
#define DRIVER_SO_H

#ifdef __cplusplus
extern "C" {
#endif

void video_driver_get_size(void);  // Signature unknown, define manually
void fbdev_backlight_init(void);  // Signature unknown, define manually
void cube_msg_thread_[...](void);  // Signature unknown, define manually
void enter_multios_app(void);  // Signature unknown, define manually
void designfilter(void);  // Signature unknown, define manually
void hcge_cmdq_paddr(void);  // Signature unknown, define manually
void api_cube_malloc(void);  // Signature unknown, define manually
void hcge_check_state(void);  // Signature unknown, define manually
void _fini(void);  // Signature unknown, define manually
void video_driver_dis[...](void);  // Signature unknown, define manually
void video_driver_setmode(void);  // Signature unknown, define manually
void sunxi_gpio_get_cfgpin(void);  // Signature unknown, define manually
void check_exit_game(void);  // Signature unknown, define manually
void api_message_delete(void);  // Signature unknown, define manually
void sound_driver_flush(void);  // Signature unknown, define manually
void hcge_fill_rect_ext(void);  // Signature unknown, define manually
void fbdev_set_enhance(void);  // Signature unknown, define manually
void sound_driver_init(void);  // Signature unknown, define manually
void video_driver_setting(void);  // Signature unknown, define manually
void exit_game(void);  // Signature unknown, define manually
void video_drivers_init(void);  // Signature unknown, define manually
void extract_phase(void);  // Signature unknown, define manually
void hcge_draw_rect(void);  // Signature unknown, define manually
void video_driver_deinit(void);  // Signature unknown, define manually
void pcm_play_task(void);  // Signature unknown, define manually
void sound_driver_pla[...](void);  // Signature unknown, define manually
void api_cube_free(void);  // Signature unknown, define manually
void hcge_state_init(void);  // Signature unknown, define manually
void sunxi_gpio_cleanup(void);  // Signature unknown, define manually
void get_multios_app(void);  // Signature unknown, define manually
void hcge_state_modif[...](void);  // Signature unknown, define manually
void _init(void);  // Signature unknown, define manually
void hcge_clip_stretc[...](void);  // Signature unknown, define manually
void api_message_get_count(void);  // Signature unknown, define manually
void pcm_decoder_flush(void);  // Signature unknown, define manually
void gpio_init(void);  // Signature unknown, define manually
void api_osd_show_onoff(void);  // Signature unknown, define manually
void hcge_get_boundin[...](void);  // Signature unknown, define manually
void pcm_decoder_init(void);  // Signature unknown, define manually
void pinmux_configure(void);  // Signature unknown, define manually
void fbdev_init(void);  // Signature unknown, define manually
void hcge_cmdq_vaddr(void);  // Signature unknown, define manually
void pcm_get_bufferin[...](void);  // Signature unknown, define manually
void sunxi_gpio_output(void);  // Signature unknown, define manually
void pinmux_init(void);  // Signature unknown, define manually
void pcm_decoder_destroy(void);  // Signature unknown, define manually
void hcge_close(void);  // Signature unknown, define manually
void pinmux_deinit(void);  // Signature unknown, define manually
void fbdev_setrotate(void);  // Signature unknown, define manually
void fbdev_video_aspe[...](void);  // Signature unknown, define manually
void hcge_matrix_tran[...](void);  // Signature unknown, define manually
void api_cube_receive_msg(void);  // Signature unknown, define manually
void set_multios_app(void);  // Signature unknown, define manually
void sunxi_gpio_input(void);  // Signature unknown, define manually
void api_cube_send_ms[...](void);  // Signature unknown, define manually
void sound_driver_deinit(void);  // Signature unknown, define manually
void hcge_engine_sync(void);  // Signature unknown, define manually
void hcge_start(void);  // Signature unknown, define manually
void gpio_deinit(void);  // Signature unknown, define manually
void hcge_reset(void);  // Signature unknown, define manually
void fbdev_get_avparam(void);  // Signature unknown, define manually
void hcge_drawingflag[...](void);  // Signature unknown, define manually
void hcge_set_state(void);  // Signature unknown, define manually
void hcge_open(void);  // Signature unknown, define manually
void fbdev_draw_frame(void);  // Signature unknown, define manually
void hcge_get_inverse[...](void);  // Signature unknown, define manually
void hcge_blit(void);  // Signature unknown, define manually
void sunxi_gpio_set_cfgpin(void);  // Signature unknown, define manually
void hcge_ge_coeff(void);  // Signature unknown, define manually
void hcge_clip_qw(void);  // Signature unknown, define manually
void gpio_configure(void);  // Signature unknown, define manually
void hcge_check_blit_state(void);  // Signature unknown, define manually
void hcge_fill_rect(void);  // Signature unknown, define manually
void api_message_create(void);  // Signature unknown, define manually
void hcge_blend_to_string(void);  // Signature unknown, define manually
void fbdev_deinit(void);  // Signature unknown, define manually
void hcge_pixelformat_name(void);  // Signature unknown, define manually
void hcge_clip_rect(void);  // Signature unknown, define manually
void gpio_get_input(void);  // Signature unknown, define manually
void designfilterff(void);  // Signature unknown, define manually
void gpio_get_configure(void);  // Signature unknown, define manually
void hcge_process_matrix(void);  // Signature unknown, define manually
void hcge_blittingfla[...](void);  // Signature unknown, define manually
void hcge_hw_reset(void);  // Signature unknown, define manually
void get_avparam_volume(void);  // Signature unknown, define manually
void cube_msg_pthread_init(void);  // Signature unknown, define manually
void api_message_rece[...](void);  // Signature unknown, define manually
void api_message_send(void);  // Signature unknown, define manually
void extract_coef(void);  // Signature unknown, define manually
void hcge_stretch_blit(void);  // Signature unknown, define manually
void api_message_crea[...](void);  // Signature unknown, define manually
void sunxi_gpio_init(void);  // Signature unknown, define manually
void hcge_feed_nodes(void);  // Signature unknown, define manually
void api_message_rece[...](void);  // Signature unknown, define manually
void gpio_set_output(void);  // Signature unknown, define manually
void hcge_matrix_multiply(void);  // Signature unknown, define manually
void pcm_decode_eos(void);  // Signature unknown, define manually
void api_message_receive(void);  // Signature unknown, define manually
void api_cube_send_msg(void);  // Signature unknown, define manually
void hcge_matrix_tran[...](void);  // Signature unknown, define manually
void hcge_construct_nodes(void);  // Signature unknown, define manually
void pcm_decode(void);  // Signature unknown, define manually
void hcge_matrix_init[...](void);  // Signature unknown, define manually
void hcge_clip_blit(void);  // Signature unknown, define manually
void hcge_clip_blit(void);  // Signature unknown, define manually
void hcge_matrix_init[...](void);  // Signature unknown, define manually
void pcm_decode(void);  // Signature unknown, define manually
void hcge_construct_nodes(void);  // Signature unknown, define manually
void video_driver_get_size(void);  // Signature unknown, define manually
void hcge_matrix_tran[...](void);  // Signature unknown, define manually
void api_cube_send_msg(void);  // Signature unknown, define manually
void fbdev_backlight_init(void);  // Signature unknown, define manually
void cube_msg_thread_[...](void);  // Signature unknown, define manually
void api_message_receive(void);  // Signature unknown, define manually
void pcm_decode_eos(void);  // Signature unknown, define manually
void hcge_matrix_multiply(void);  // Signature unknown, define manually
void gpio_set_output(void);  // Signature unknown, define manually
void api_message_rece[...](void);  // Signature unknown, define manually
void enter_multios_app(void);  // Signature unknown, define manually
void designfilter(void);  // Signature unknown, define manually
void hcge_feed_nodes(void);  // Signature unknown, define manually
void sunxi_gpio_init(void);  // Signature unknown, define manually
void hcge_cmdq_paddr(void);  // Signature unknown, define manually
void api_message_crea[...](void);  // Signature unknown, define manually
void api_cube_malloc(void);  // Signature unknown, define manually
void hcge_stretch_blit(void);  // Signature unknown, define manually
void extract_coef(void);  // Signature unknown, define manually
void api_message_send(void);  // Signature unknown, define manually
void api_message_rece[...](void);  // Signature unknown, define manually
void hcge_check_state(void);  // Signature unknown, define manually
void cube_msg_pthread_init(void);  // Signature unknown, define manually
void _fini(void);  // Signature unknown, define manually
void get_avparam_volume(void);  // Signature unknown, define manually
void hcge_hw_reset(void);  // Signature unknown, define manually
void hcge_blittingfla[...](void);  // Signature unknown, define manually
void hcge_process_matrix(void);  // Signature unknown, define manually
void video_driver_dis[...](void);  // Signature unknown, define manually
void video_driver_setmode(void);  // Signature unknown, define manually
void sunxi_gpio_get_cfgpin(void);  // Signature unknown, define manually
void check_exit_game(void);  // Signature unknown, define manually
void gpio_get_configure(void);  // Signature unknown, define manually
void designfilterff(void);  // Signature unknown, define manually
void gpio_get_input(void);  // Signature unknown, define manually
void api_message_delete(void);  // Signature unknown, define manually
void sound_driver_flush(void);  // Signature unknown, define manually
void hcge_clip_rect(void);  // Signature unknown, define manually
void hcge_fill_rect_ext(void);  // Signature unknown, define manually
void hcge_pixelformat_name(void);  // Signature unknown, define manually
void fbdev_set_enhance(void);  // Signature unknown, define manually
void fbdev_deinit(void);  // Signature unknown, define manually
void hcge_blend_to_string(void);  // Signature unknown, define manually
void api_message_create(void);  // Signature unknown, define manually
void hcge_fill_rect(void);  // Signature unknown, define manually
void hcge_check_blit_state(void);  // Signature unknown, define manually
void sound_driver_init(void);  // Signature unknown, define manually
void gpio_configure(void);  // Signature unknown, define manually
void video_driver_setting(void);  // Signature unknown, define manually
void hcge_clip_qw(void);  // Signature unknown, define manually
void hcge_ge_coeff(void);  // Signature unknown, define manually
void sunxi_gpio_set_cfgpin(void);  // Signature unknown, define manually
void exit_game(void);  // Signature unknown, define manually
void video_drivers_init(void);  // Signature unknown, define manually
void hcge_blit(void);  // Signature unknown, define manually
void extract_phase(void);  // Signature unknown, define manually
void hcge_draw_rect(void);  // Signature unknown, define manually
void hcge_get_inverse[...](void);  // Signature unknown, define manually
void fbdev_draw_frame(void);  // Signature unknown, define manually
void hcge_open(void);  // Signature unknown, define manually
void hcge_set_state(void);  // Signature unknown, define manually
void hcge_drawingflag[...](void);  // Signature unknown, define manually
void fbdev_get_avparam(void);  // Signature unknown, define manually
void hcge_reset(void);  // Signature unknown, define manually
void video_driver_deinit(void);  // Signature unknown, define manually
void gpio_deinit(void);  // Signature unknown, define manually
void pcm_play_task(void);  // Signature unknown, define manually
void hcge_start(void);  // Signature unknown, define manually
void hcge_engine_sync(void);  // Signature unknown, define manually
void sound_driver_pla[...](void);  // Signature unknown, define manually
void sound_driver_deinit(void);  // Signature unknown, define manually
void api_cube_send_ms[...](void);  // Signature unknown, define manually
void sunxi_gpio_input(void);  // Signature unknown, define manually
void api_cube_free(void);  // Signature unknown, define manually
void set_multios_app(void);  // Signature unknown, define manually
void api_cube_receive_msg(void);  // Signature unknown, define manually
void hcge_matrix_tran[...](void);  // Signature unknown, define manually
void fbdev_video_aspe[...](void);  // Signature unknown, define manually
void fbdev_setrotate(void);  // Signature unknown, define manually
void hcge_state_init(void);  // Signature unknown, define manually
void sunxi_gpio_cleanup(void);  // Signature unknown, define manually
void pinmux_deinit(void);  // Signature unknown, define manually
void hcge_close(void);  // Signature unknown, define manually
void pcm_decoder_destroy(void);  // Signature unknown, define manually
void get_multios_app(void);  // Signature unknown, define manually
void pinmux_init(void);  // Signature unknown, define manually
void sunxi_gpio_output(void);  // Signature unknown, define manually
void pcm_get_bufferin[...](void);  // Signature unknown, define manually
void hcge_cmdq_vaddr(void);  // Signature unknown, define manually
void fbdev_init(void);  // Signature unknown, define manually
void pinmux_configure(void);  // Signature unknown, define manually
void hcge_state_modif[...](void);  // Signature unknown, define manually
void pcm_decoder_init(void);  // Signature unknown, define manually
void hcge_get_boundin[...](void);  // Signature unknown, define manually
void api_osd_show_onoff(void);  // Signature unknown, define manually
void gpio_init(void);  // Signature unknown, define manually
void _init(void);  // Signature unknown, define manually
void hcge_clip_stretc[...](void);  // Signature unknown, define manually
void pcm_decoder_flush(void);  // Signature unknown, define manually
void api_message_get_count(void);  // Signature unknown, define manually

#ifdef __cplusplus
}
#endif

#endif // DRIVER_SO_H