
CC = mipsel-linux-gnu-gcc
CFLAGS = -nostdlib -static -Os
TARGET = sf3000_memdebug
SRCS = sf3000_memdebug.c

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET)
